import { ImageResponse } from "next/og";
import QRCode from "qrcode";
import APP from "@/constants/app";
import {
  ASSET_COPY,
  PARTNER_ASSETS,
  PARTNER_KITS,
  type PartnerAssetId,
} from "@/constants/partner-kits";
import { loadOgAssets, ogFonts, OG_CACHE_CONTROL } from "@/lib/og";

export const runtime = "nodejs";

const BRAND = "#f25322";
const BG = "#161616";
const BORDER = "rgba(255,255,255,0.06)";
const TEXT = "#f6f6f6";
const MUTED = "#8a8a8a";

/**
 * A creator's Twitch asset, rendered on demand rather than kept as a file.
 *
 * Same machinery as the OG cards (`next/og`, the shared Figtree buffers and the
 * logo data URL), for the same reason: the alternative is a folder of binaries
 * per creator, regenerated by hand every time the brand or a label moves. Here a
 * new partner is one entry in `PARTNER_KITS` and nothing else.
 *
 * Satori constraints worth knowing before editing: every container needs an
 * explicit `display: flex`, there is no grid, and `background-image` patterns
 * are not supported (which is why the hatch the site uses is absent here).
 */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ slug: string; asset: string }> },
) {
  const { slug, asset } = await params;
  const kit = PARTNER_KITS[slug];
  const spec = PARTNER_ASSETS[asset as PartnerAssetId];
  if (!kit || !spec) return new Response("Not found", { status: 404 });

  const { regular, bold, logoSrc } = await loadOgAssets();
  // The images carry the creator's language, not the site's: they are pixels,
  // so nothing downstream can translate them for their audience.
  const copy = ASSET_COPY[kit.locale];
  const url = `unicum.gg/${slug}`;
  const compact = asset === "overlay-compact";
  const offline = asset === "offline" || asset === "offline-qr";

  let qrSrc: string | null = null;
  if (asset === "offline-qr") {
    // Highest error correction: the code is printed small on a stream layout
    // and read off a screen, often at an angle.
    qrSrc = await QRCode.toDataURL(
      `${APP.URL}/${slug}?utm_source=twitch&utm_medium=qr&utm_campaign=${slug}`,
      { errorCorrectionLevel: "H", margin: 1, width: 300,
        color: { dark: BG, light: "#ffffff" } },
    ).catch(() => null);
  }

  const wordmark = (size: number) => (
    <div style={{ display: "flex", fontSize: size, fontWeight: 700, color: TEXT, letterSpacing: -0.5 }}>
      unicum.gg
      {/* Rendered as its own node with a left margin: the tight tracking above
          otherwise runs the slash into the second g. */}
      <div style={{ display: "flex", color: BRAND, marginLeft: size * 0.03 }}>/{slug}</div>
    </div>
  );

  const body = offline ? (
    <div style={{ width: "100%", height: "100%", display: "flex", alignItems: "center",
                  justifyContent: "center", gap: 92, backgroundColor: BG }}>
      <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 22 }}>
        <img src={logoSrc} width={104} height={142} alt="" />
        <div style={{ display: "flex", fontSize: 78, fontWeight: 700, color: TEXT, letterSpacing: -2.4 }}>
          unicum<div style={{ display: "flex", color: BRAND }}>.gg</div>
        </div>
        <div style={{ display: "flex", fontSize: 24, color: MUTED }}>
          {copy.tagline}
        </div>
        <div style={{ display: "flex", width: 130, height: 1, backgroundColor: "rgba(255,255,255,0.1)" }} />
        <div style={{ display: "flex", fontSize: 28, fontWeight: 700, color: BRAND }}>{url}</div>
      </div>
      {qrSrc ? (
        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 16 }}>
          <img src={qrSrc} width={300} height={300} alt=""
               style={{ border: "12px solid #fff", borderRadius: 10 }} />
          <div style={{ display: "flex", fontSize: 16, fontWeight: 700, color: MUTED, letterSpacing: 1.4 }}>
            {copy.scan}
          </div>
        </div>
      ) : null}
    </div>
  ) : asset === "panel" ? (
    <div style={{ width: "100%", height: "100%", display: "flex", flexDirection: "column",
                  backgroundColor: BG, border: `1px solid ${BORDER}`, borderRadius: 10 }}>
      <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center",
                    justifyContent: "center", gap: 11 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <img src={logoSrc} width={26} height={36} alt="" />
          <div style={{ display: "flex", fontSize: 21, fontWeight: 700, color: TEXT, letterSpacing: -0.4 }}>
            unicum<div style={{ display: "flex", color: BRAND }}>.gg</div>
          </div>
        </div>
        <div style={{ display: "flex", fontSize: 11.5, color: MUTED }}>
          {copy.tagline}
        </div>
      </div>
      <div style={{ height: 34, display: "flex", alignItems: "center", justifyContent: "center",
                    borderTop: `1px solid ${BORDER}`, backgroundColor: "rgba(255,255,255,0.02)" }}>
        <div style={{ display: "flex", fontSize: 12, fontWeight: 700, color: BRAND, letterSpacing: 0.9 }}>
          {url.toUpperCase()}
        </div>
      </div>
    </div>
  ) : (
    <div style={{ width: "100%", height: "100%", display: "flex", padding: "0 16px",
                  gap: compact ? 0 : 12, backgroundColor: BG,
                  border: `1px solid ${BORDER}`, borderLeft: `3px solid ${BRAND}`,
                  borderRadius: 10,
                  flexDirection: compact ? "column" : "row",
                  justifyContent: "center",
                  alignItems: compact ? "flex-start" : "center" }}>
      {compact ? null : <img src={logoSrc} width={30} height={41} alt="" />}
      <div style={{ display: "flex", flexDirection: "column", gap: compact ? 4 : 3 }}>
        {compact ? null : (
          <div style={{ display: "flex", fontSize: 10, fontWeight: 700, color: MUTED, letterSpacing: 1.5 }}>
            {copy.kicker}
          </div>
        )}
        {wordmark(compact ? 21 : 22)}
        {compact ? (
          <div style={{ display: "flex", fontSize: 10, fontWeight: 700, color: MUTED, letterSpacing: 1.4 }}>
            {copy.kickerYours}
          </div>
        ) : null}
      </div>
    </div>
  );

  return new ImageResponse(body, {
    width: spec.width,
    height: spec.height,
    fonts: ogFonts({ regular, bold, logoSrc }),
    headers: { "Cache-Control": OG_CACHE_CONTROL },
  });
}
